### ISSUE TITLE
FDroid version update

### ISSUE THREAD

**Issue by homlett** [kiwix/kiwix-xulrunner#312] opened 2016-09-15 16:52 UTC
Kiwix for Android sounds great, but it should to be updated.

**Comment by kelson42** [comment] 2016-09-15 18:47
@homlett Why not asking the FDroid team?

**Comment by mhutti1** [comment] 2016-09-15 18:50
@kelson42 I think he is asking why fdroid version is 1.97 but google play version is 1.99

**Comment by kelson42** [comment] 2016-09-15 18:51
@mhutti1 I don't know. The question should be asked to the FDroid team. I have tried to ping them a little bit without success. Now, the best is to release 2.0 and then ask again I think.

**Comment by mhutti1** [comment] 2016-09-15 18:53
@kelson42 Ok I might look into it a bit after 2.0 release.

**Comment by kelson42** [comment] 2016-12-04 20:26
The problem is that they have a strange Python problem. They told me they will retry but no news. I have asked again today someone of the Fdroid team.

**Comment by kelson42** [comment] 2017-02-13 18:56
@rashiq Could you please have a special look to this ticket as you know personnaly mvdan and are familliar with both Android an Python?

**Comment by rashiq** [comment] 2017-02-13 18:57
@kelson42 will do! I only noticed a few days ago that the kiwix version on fdroid is very outdated

**Comment by kelson42** [comment] 2017-02-13 18:59
@rashiq Thx very much. Yes, because (what looks like to be) a silly Python bug/problem, FDroid is behind our release mgmt of more than 6 months.

**Comment by mvdan** [comment] 2017-03-04 21:18
@rashiq did indeed stalk me in real life, so I'm having a look at the moment.

To provide some context, Kiwix is one of the more complex builds on the main repo so it makes sense that it would easily fall behind unless someone actively works on updates.

**Comment by mvdan** [comment] 2017-03-04 22:12
This took a while, but got a build working. Pushed https://gitlab.com/fdroid/fdroiddata/commit/6e10f23954ed608ccf6a1cbad5741886dfdaa21b.

**Comment by rashiq** [comment] 2017-03-04 22:24
Thanks again @mvdan :)

**Comment by kelson42** [comment] 2017-03-05 10:40
@mvdan @rashiq Thank you very much for the good work. @mgautierfr is currently working to revamp compilation scripts for the whole project (Android included). Things should be over next week for Android. It should make the maintenance work on FDroid side easier. I least we hope so... let see for the next releases :)

**Comment by mvdan** [comment] 2017-03-12 19:42
This is really weird - the build worked locally, but we're hitting the same utf8 error on the buildserver: https://f-droid.org/wiki/page/org.kiwix.kiwixmobile/lastbuild_45

I've filed a very probable fix for this in our python codebase: https://gitlab.com/fdroid/fdroidserver/merge_requests/224

When I first encountered this crash, I think my understanding of encodings in Python just wasn't good enough to figure out a proper fix. This still isn't perfect - it will ignore the bytes - but it's certainly better than a crash.

Will update this issue if there are any news.

**Comment by mvdan** [comment] 2017-03-15 12:33
There happens to be a huge backlog of apps with failing builds, so this is taking longer than usual. Still waiting on a build with the updated python code.

**Comment by mvdan** [comment] 2017-03-16 11:19
Finally succeeded: https://f-droid.org/wiki/page/org.kiwix.kiwixmobile/lastbuild_45

The index update will happen in a few hours - then it will be visible on https://f-droid.org/app/org.kiwix.kiwixmobile

**Comment by rashiq** [comment] 2017-03-16 14:49
Awesome! Thanks :)

Daniel Martí <notifications@github.com> schrieb am Do., 16. März 2017,
12:19:

**Comment by kelson42** [comment] 2017-03-18 10:56
@mvdan I just saw this morning that Kiwix has been updated on my Fdroid! Yohoo! Then I remarked... that this is not the last version: this is version 2.1 and we have released 2.2 a few weeks ago. Not sure the reason why, maybe because we did not had tagged the git for Kiwix git repo correctly. Anyway, I have done this now https://github.com/kiwix/kiwix/releases/tag/android_v2.20... and may you please try to update to 2.2?

**Comment by mhutti1** [comment] 2017-03-18 12:39
This issue was moved to kiwix/kiwix-android#61

**Closed as completed by mhutti1** 2017-03-18 12:39 UTC
Labels: android
