### ISSUE TITLE
Downloads stick to the notification bar even if Kiwix is closed.

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#432] opened 2017-01-08 23:49 UTC
* If Kiwix runs, IMO it should be possible to remove the download notifications. For now, it seems impossible to rmove them.
* If Kiwix as been stop, IMO they should automatically vanish. For now they still stick to the notifications.

**Comment by mhutti1** [comment] 2017-01-08 23:52
@kelson42  This is by design. In order for our app to continue downloading without being killed by the system we must keep an undismmisable notification up.

**Comment by EladKeyshawn** [comment] 2017-01-09 05:49
@mhutti1 @kelson42 We can also add a pause and continue button

**Comment by kelson42** [comment] 2017-01-09 06:52
@mhutti1 OK for case 1, but if the app does not run, then no download is running? So the notification might be removed?

**Comment by kelson42** [comment] 2017-01-09 06:52
@EladKeyshawn Might be nice, but this should be handle in an other ticket.

**Comment by mhutti1** [comment] 2017-01-14 23:38
@kelson42 I have implemented the interface buttons. In regards to this issue, I don't think its a good idea to remove the notifications automatically as the user might be downloading a large file and leave it running checking the notification every now and again. What do you think?

**Comment by kelson42** [comment] 2017-01-15 14:08
@mhutti1 Thank you for going ahead on this and implementing the buttons. I think if the notification sticks and the download goes ahead in the background - this makes sense. But, if for some reason, the download does not run in background (android has restarted, app was forced to close, ...) then the notification should disappear (and reappear if the download restarts). Is that possible?

**Comment by mhutti1** [comment] 2017-01-15 14:27
@kelson42 The notifications are directly tied to our download service by the Android system. If our service is killed so our our notifications. If android is restarted notifications also disappear so I think that this should not be possible.

**Comment by kelson42** [comment] 2017-01-22 15:20
@mhutti1 By downloading two content at the same time, the "Pause" and "Stop" buttons appear only in the notification of the first download. The second download is like before. Tested by downloading both (withpic and nopic) Wikimedia English ZIM files.

**Comment by EladKeyshawn** [comment] 2017-01-22 15:23
@kelson42 @mhutti1 Also the "Pause" and "Stop" buttons keep disappearing, probably because of the progress bar updating causes the buttons to hide somehow.

**Comment by mhutti1** [comment] 2017-01-22 15:25
@kelson42 @EladKeyshawn No thats not the issue. Android automatically hides them. You can see the buttons by expanding the notification (at least in 7.0). It seems they might not work correctly though with more than one notification.

**Comment by kelson42** [comment] 2017-01-22 15:27
@mhutti1 I confirm this.  so forget about my last comment about stop/pause buttons. It works.

**Comment by kelson42** [comment] 2017-01-22 15:40
@mhutti1 By downloading the two Wikimed in English at the same time, the stop button in the notification works only for the first one.

**Comment by mhutti1** [comment] 2017-01-22 16:27
@kelson42 this should be fixed now.

**Comment by kelson42** [comment] 2017-01-22 17:00
@mhutti1 I confirm

**Comment by kelson42** [comment] 2017-01-22 17:01
I close the ticket. It seems to work fine now. Thank you @EladKeyshawn @mhutti1 for working on the solution

**Closed as completed** 2017-01-22 18:06 UTC
Labels: enhancement, android
