### ISSUE TITLE
Kiwix 0.9 keeps asking to re-index .zim files.

### ISSUE THREAD

**Issue by khanhhung2512** [kiwix/kiwix-xulrunner#358] opened 2016-11-12 14:06 UTC
I'm on Windows 10 64-bit. I downloaded the Kiwix 0.9 with English Wikipedia, and it works fine. However, I later downloaded another .zim file and had it opened by Kiwix. Kiwix took a while to index that file. However, everytime I sign out (log out) of the windows account and sign in again, Kiwix forgets that file (and the file disappears from library) and asks me to re-index that file. Apparently, it doesn't take any time to re-index that file, fortunately. Still, is there any way to fix that issue?

Btw, I also need to kill the xulrunner process every time I close Kiwix and reopen it again. Happens in both Windows 7 64-bit and Windows 10 64-bit.

**Comment by kelson42** [comment] 2016-11-13 13:14
@khanhhung2512 I do not have an easy answer. It looks like the local library xml file is not updated correctly. Regarding the last bug, a few people already reported it... but I was not able to reproduce it. We are currently working on the next generation of Kiwix reader and we hope these bugs will be fixed.

**Comment by kelson42** [comment] 2019-06-16 15:20
New version 2.0 of Kiwix Desktop does not allow to index content, as the index is already embedded in the ZIM file. This solve the bug.

**Closed as completed by kelson42** 2019-06-16 15:20 UTC
Labels: bug
