### ISSUE TITLE
Search issue with directional unicode characters

### ISSUE THREAD

**Issue by ISNIT0** [kiwix/kiwix-xulrunner#248] opened 2016-06-20 14:50 UTC
![screen shot 2016-06-20 at 16 48 42](https://cloud.githubusercontent.com/assets/5173131/16198674/febaa1ca-3706-11e6-82e1-465269b2480c.png)

One cannot search for an item by title when the title begins with (in some cases important) directional unicode characters.

Perhaps the search could apply the reversal then search?

**Comment by kelson42** [comment] 2016-06-21 13:19
The problem is that these characters are included in the ZIM file title index and impair the suggestion system. I have updated zimwriterfs to remove them and bug should be fixed.

**Closed as completed by kelson42** 2016-06-21 13:19 UTC
