### ISSUE TITLE
zim

### ISSUE THREAD

**Issue by amirh123123** [kiwix/kiwix-xulrunner#497] opened 2018-01-21 19:47 UTC
I mean, convert the files that are on the page to Zim
address
http://dev.worldpossible.org/cgi/rachelmods.pl
example i download MedlinePlus but not zim please convert files to zim thanks

**Comment by kelson42** [comment] 2019-06-16 15:19
Duplicate of https://github.com/openzim/zim-requests/issues/86

**Closed as completed by kelson42** 2019-06-16 15:19 UTC
Labels: duplicate
